package com.dwolla.util.async.finagle.otel4s

import cats.*
import cats.effect.*
import cats.effect.std.Dispatcher
import cats.effect.syntax.all.*
import cats.syntax.all.*
import cats.tagless.aop.*
import cats.tagless.implicits.*
import com.comcast.ip4s.{IpAddress, SocketAddress}
import com.dwolla.util.async.finagle.HigherKindedToMethodPerEndpoint.*
import com.dwolla.util.async.finagle.{B3MultiHeaders, HigherKindedToMethodPerEndpoint}
import com.dwolla.util.async.twitter.*
import com.twitter.finagle.*
import com.twitter.finagle.tracing.TraceId
import com.twitter.util.{Future, Promise}
import org.typelevel.otel4s.trace.{SpanBuilder, SpanKind, Tracer, TracerProvider}

import scala.concurrent.ExecutionContext
import scala.util.{Failure, Success}

/**
 * Starts a Finagle server that will host the given Thrift
 * method-per-endpoint implementation, tracing each request with otel4s.
 */
object TracedThriftServer {
  /**
   * The instrumentation scope name of the `Tracer` this server obtains from the `TracerProvider`.
   */
  val InstrumentationScopeName: String = "com.dwolla.util.async.finagle.otel4s"

  /**
   * Builds a `ListeningServer` that wraps each Thrift request in an otel4s `SpanKind.Server` span named
   * `{algebraName}.{methodName}`.
   *
   * If Finagle received a `TraceId` with the request, the span continues that trace: the `TraceId` is
   * rendered as Zipkin B3 multi-headers (`X-B3-TraceId`, `X-B3-SpanId`, etc.) and handed to
   * `Tracer.joinOrRoot`, so the application's otel4s propagators must include B3 (e.g.
   * `OTEL_PROPAGATORS=tracecontext,baggage,b3multi`) for the trace to be continued. Otherwise, the span
   * is the root of a new trace.
   *
   * @param addr  the socket address at which to listen for connections. (Typically `0.0.0.0:port`)
   * @param label the label Finagle assigns to the server
   * @param iface the Thrift method-per-endpoint implementation. The request's server span is the current span while it runs.
   * @param ec    `ExecutionContext` where Twitter Futures will be completed when the Scala Future output by `Dispatcher.unsafeToFuture` completes
   * @tparam F      the effect in which to operate, which must have `Async[F]` and `TracerProvider[F]` instances available
   * @tparam Thrift the higher-kinded MethodPerEndpoint Thrift algebra generated by scrooge and modified by the `AddCatsTaglessInstances` scalafix
   * @return a `Resource[F, ListeningServer]` managing the lifecycle of the underlying Finagle server
   */
  def apply[F[_] : Async : TracerProvider, Thrift[_[_]] : HigherKindedToMethodPerEndpoint : Instrument](addr: SocketAddress[IpAddress],
                                                                                                         label: String,
                                                                                                         iface: Thrift[F],
                                                                                                        )
                                                                                                        (implicit ec: ExecutionContext): Resource[F, ListeningServer] =
    TracedThriftServer(addr, label, iface, identity[SpanBuilder[F]])

  /**
   * Builds a `ListeningServer` that wraps each Thrift request in an otel4s `SpanKind.Server` span named
   * `{algebraName}.{methodName}`. See the other overload for details about how traces are continued.
   *
   * @param addr          the socket address at which to listen for connections. (Typically `0.0.0.0:port`)
   * @param label         the label Finagle assigns to the server
   * @param iface         the Thrift method-per-endpoint implementation. The request's server span is the current span while it runs.
   * @param customizeSpan customizes the `SpanBuilder` for each request's span, after its name and `SpanKind.Server` have been set
   * @param ec            `ExecutionContext` where Twitter Futures will be completed when the Scala Future output by `Dispatcher.unsafeToFuture` completes
   * @tparam F      the effect in which to operate, which must have `Async[F]` and `TracerProvider[F]` instances available
   * @tparam Thrift the higher-kinded MethodPerEndpoint Thrift algebra generated by scrooge and modified by the `AddCatsTaglessInstances` scalafix
   * @return a `Resource[F, ListeningServer]` managing the lifecycle of the underlying Finagle server
   */
  def apply[F[_] : Async : TracerProvider, Thrift[_[_]] : HigherKindedToMethodPerEndpoint : Instrument](addr: SocketAddress[IpAddress],
                                                                                                         label: String,
                                                                                                         iface: Thrift[F],
                                                                                                         customizeSpan: SpanBuilder[F] => SpanBuilder[F],
                                                                                                        )
                                                                                                        (implicit ec: ExecutionContext): Resource[F, ListeningServer] =
    for {
      tracer <- TracerProvider[F].get(InstrumentationScopeName).toResource
      dispatcher <- Dispatcher.parallel[F]
      server <- Resource.make(acquire(addr, label, iface.instrument.mapK(new UnsafeInstrumentationToFuture[F](dispatcher, tracer, customizeSpan))))(release[F])
    } yield server

  private def currentTraceId(): Future[Option[TraceId]] =
    Future(com.twitter.finagle.tracing.Trace.idOption)

  // Finagle's own tracer is left as the default: otel4s exports the server span itself.
  private def acquire[F[_] : Sync, Thrift[_[_]] : HigherKindedToMethodPerEndpoint](addr: SocketAddress[IpAddress],
                                                                                   label: String,
                                                                                   iface: Thrift[Future]): F[ListeningServer] =
    Sync[F].delay {
      Thrift
        .server
        .withLabel(label)
        .serveIface(addr.toInetSocketAddress, iface.toMethodPerEndpoint)
    }

  private def release[F[_] : Async](s: ListeningServer): F[Unit] =
    liftFuture(Sync[F].delay(s.close()))

  private class UnsafeInstrumentationToFuture[F[_]](dispatcher: Dispatcher[F],
                                                    tracer: Tracer[F],
                                                    customizeSpan: SpanBuilder[F] => SpanBuilder[F],
                                                   )
                                                   (implicit ec: ExecutionContext) extends (Instrumentation[F, *] ~> Future) {
    override def apply[A](instrumentation: Instrumentation[F, A]): Future[A] =
      currentTraceId().flatMap { maybeTraceId =>
        val p = Promise[A]()

        val span =
          customizeSpan(tracer.spanBuilder(s"${instrumentation.algebraName}.${instrumentation.methodName}").withSpanKind(SpanKind.Server))
            .build

        // with no Finagle TraceId, the empty carrier makes joinOrRoot start a root span, rather than
        // a child of whatever span was current when the Dispatcher was created
        val fa = tracer.joinOrRoot(maybeTraceId.foldMap(B3MultiHeaders.fromTraceId))(span.surround(instrumentation.value))

        dispatcher.unsafeToFuture(fa)
          .onComplete {
            case Success(a) => p.setValue(a)
            case Failure(ex) => p.setException(ex)
          }

        p
      }
  }

}
