/*
rule = AddCatsTaglessInstances
 */
/**
 * Generated by Scrooge
 *   version: 21.8.0
 *   rev: 75b832815f5da5328f0225e2ab3e06a14afb3446
 *   built at: 20210813-170828
 */
package example.thrift

import com.twitter.finagle.{service => ctfs}
import com.twitter.finagle.stats.{NullStatsReceiver, StatsReceiver}
import com.twitter.finagle.thrift.{Protocols, RichClientParam, ThriftClientRequest}
import com.twitter.util.Future
import org.apache.thrift.TApplicationException
import org.apache.thrift.protocol._


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
class SimpleService$FinagleClient(
    val service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
    val clientParam: RichClientParam)
  extends SimpleService[Future] {

  @deprecated("Use com.twitter.finagle.thrift.RichClientParam", "2017-08-16")
  def this(
    service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
    protocolFactory: TProtocolFactory = Protocols.binaryFactory(),
    serviceName: String = "SimpleService",
    stats: StatsReceiver = NullStatsReceiver,
    responseClassifier: ctfs.ResponseClassifier = ctfs.ResponseClassifier.Default
  ) = this(
    service,
    RichClientParam(
      protocolFactory,
      serviceName,
      clientStats = stats,
      responseClassifier = responseClassifier
    )
  )

  import SimpleService._

  def serviceName: String = clientParam.serviceName

  override def asClosable: _root_.com.twitter.util.Closable = service

  private[this] def protocolFactory: TProtocolFactory = clientParam.restrictedProtocolFactory

  private[this] val tlReusableBuffer: _root_.com.twitter.scrooge.TReusableBuffer =
    clientParam.createThriftReusableBuffer()

  protected def encodeRequest(name: String, args: _root_.com.twitter.scrooge.ThriftStruct): ThriftClientRequest = {
    val memoryBuffer = tlReusableBuffer.get()
    try {
      val oprot = protocolFactory.getProtocol(memoryBuffer)

      oprot.writeMessageBegin(new TMessage(name, TMessageType.CALL, 0))
      args.write(oprot)
      oprot.writeMessageEnd()
      oprot.getTransport.flush()
      val bytes = _root_.java.util.Arrays.copyOfRange(
        memoryBuffer.getArray(),
        0,
        memoryBuffer.length()
      )
      new ThriftClientRequest(bytes, false)
    } finally {
      tlReusableBuffer.reset()
    }
  }

  protected def decodeResponse[T <: _root_.com.twitter.scrooge.ThriftStruct](
    resBytes: Array[Byte],
    codec: _root_.com.twitter.scrooge.ThriftStructCodec[T]
  ): _root_.com.twitter.util.Try[T] =
    _root_.com.twitter.finagle.thrift.service.ThriftCodec.decodeResponse(resBytes, codec, protocolFactory, serviceName)

  // ----- end boilerplate.

  private[this] def stats: StatsReceiver = clientParam.clientStats
  private[this] def responseClassifier: ctfs.ResponseClassifier = clientParam.responseClassifier

  private[this] val scopedStats: StatsReceiver = if (serviceName != "") stats.scope(serviceName) else stats
  private[this] object __stats_makeRequest {
    val RequestsCounter: _root_.com.twitter.finagle.stats.Counter = scopedStats.scope("MakeRequest").counter("requests")
    val SuccessCounter: _root_.com.twitter.finagle.stats.Counter = scopedStats.scope("MakeRequest").counter("success")
    val FailuresCounter: _root_.com.twitter.finagle.stats.Counter = scopedStats.scope("MakeRequest").counter("failures")
    val FailuresScope: StatsReceiver = scopedStats.scope("MakeRequest").scope("failures")
  }
  val MakeRequestSimpleServiceReplyDeserializer: Array[Byte] => _root_.com.twitter.util.Try[example.thrift.SimpleResponse] = {
    response: Array[Byte] => {
      decodeResponse(response, MakeRequest.Result).flatMap { result: MakeRequest.Result =>
        val firstException = result.firstException()
        if (firstException.isDefined) {
          _root_.com.twitter.util.Throw(_root_.com.twitter.finagle.SourcedException.setServiceName(firstException.get, serviceName))
        } else if (result.successField.isDefined) {
          _root_.com.twitter.util.Return(result.successField.get)
        } else {
          _root_.com.twitter.util.Throw(_root_.com.twitter.scrooge.internal.ApplicationExceptions.missingResult("MakeRequest"))
        }
      }
    }
  }
  
  def makeRequest(request: example.thrift.SimpleRequest): Future[example.thrift.SimpleResponse] = {
    __stats_makeRequest.RequestsCounter.incr()
    val inputArgs = MakeRequest.Args(request)
  
    val serdeCtx = new _root_.com.twitter.finagle.thrift.ClientDeserializeCtx[example.thrift.SimpleResponse](inputArgs, MakeRequestSimpleServiceReplyDeserializer)
    _root_.com.twitter.finagle.context.Contexts.local.let(
      _root_.com.twitter.finagle.thrift.ClientDeserializeCtx.Key,
      serdeCtx,
      _root_.com.twitter.finagle.thrift.Headers.Request.Key,
      _root_.com.twitter.finagle.thrift.Headers.Request.newValues
    ) {
      serdeCtx.rpcName("MakeRequest")
      val start = System.nanoTime
      val serialized = encodeRequest("MakeRequest", inputArgs)
      serdeCtx.serializationTime(System.nanoTime - start)
      this.service(serialized).flatMap { response =>
        Future.const(serdeCtx.deserialize(response))
      }.respond { response =>
        val classified = responseClassifier.applyOrElse(
          ctfs.ReqRep(inputArgs, response),
          ctfs.ResponseClassifier.Default)
        if (classified.isInstanceOf[ctfs.ResponseClass.Successful]) {
          __stats_makeRequest.SuccessCounter.incr()
        } else if (classified.isInstanceOf[ctfs.ResponseClass.Failed]) {
          __stats_makeRequest.FailuresCounter.incr()
          if (response.isThrow) {
            _root_.com.twitter.finagle.SourcedException.setServiceName(response.throwable, serviceName)
            __stats_makeRequest.FailuresScope.counter(
              _root_.com.twitter.util.Throwables.mkString(response.throwable): _*).incr()
          }
        } // Last ResponseClass is Ignorable, which we do not need to record
      }
    }
  }
}
