/**
 * Generated by Scrooge
 *   version: 22.7.0
 *   rev: 2bb5fe76210bd2837988f9703fc9ca47d51bbe26
 *   built at: 20220728-182510
 */
package example.thrift

import com.twitter.scrooge._
import com.twitter.finagle.{
  service => ctfs,
  Filter => finagle$Filter,
  Service => finagle$Service,
  thrift => _,
  _
}
import com.twitter.finagle.stats.{Counter, StatsReceiver}
import com.twitter.finagle.thrift.{
  Protocols,
  RichClientParam,
  RichServerParam,
  ServerToReqRep,
  ThriftClientRequest,
  ToThriftService
}
import com.twitter.util.{Future, Return, Throw, Throwables}
import com.twitter.io.Buf
import org.apache.thrift.protocol._
import org.apache.thrift.TApplicationException
import scala.collection.mutable.Builder
import scala.collection.immutable.{Map => immutable$Map, Set => immutable$Set}
import scala.language.higherKinds
import scala.reflect.{ClassTag, classTag}


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
object SimpleService extends _root_.com.twitter.finagle.thrift.GeneratedThriftService { self =>

  val annotations: immutable$Map[String, String] = immutable$Map.empty

  val methods: immutable$Set[ThriftMethod] = immutable$Set(
    self.MakeRequest
  )

  trait ServicePerEndpoint
    extends ToThriftService
    with _root_.com.twitter.finagle.thrift.service.Filterable[ServicePerEndpoint] {
    def makeRequest : _root_.com.twitter.finagle.Service[self.MakeRequest.Args, self.MakeRequest.SuccessType]

    def withMakeRequest(makeRequest : _root_.com.twitter.finagle.Service[self.MakeRequest.Args, self.MakeRequest.SuccessType]): ServicePerEndpoint = this

    /**
     * Prepends the given type-agnostic `Filter` to all of the `Services`
     * and returns a copy of the `ServicePerEndpoint` now including the filter.
     */
    def filtered(filter: _root_.com.twitter.finagle.Filter.TypeAgnostic): ServicePerEndpoint =
      ServicePerEndpoint.apply(makeRequest).filtered(filter)

    /**
     * Converts the `ServicePerEndpoint` to a `GeneratedThriftService`.
     * @see _root_.com.twitter.scrooge.ToThriftService
     */
    def toThriftService: _root_.com.twitter.finagle.thrift.ThriftService = MethodPerEndpoint(this)

    /**
     * Used to close the underlying `Service`.
     * Not a user-defined API.
     */
    def asClosable: _root_.com.twitter.util.Closable = _root_.com.twitter.util.Closable.nop
  }

  trait ReqRepServicePerEndpoint
    extends ToThriftService
    with _root_.com.twitter.finagle.thrift.service.Filterable[ReqRepServicePerEndpoint] {
    def makeRequest : _root_.com.twitter.finagle.Service[com.twitter.scrooge.Request[self.MakeRequest.Args], _root_.com.twitter.scrooge.Response[self.MakeRequest.SuccessType]]

    def withMakeRequest(makeRequest : _root_.com.twitter.finagle.Service[com.twitter.scrooge.Request[self.MakeRequest.Args], _root_.com.twitter.scrooge.Response[self.MakeRequest.SuccessType]]): ReqRepServicePerEndpoint = this

    /**
     * Prepends the given type-agnostic `Filter` to all of the `Services`
     * and returns a copy of the `ServicePerEndpoint` now including the filter.
     */
    def filtered(filter: com.twitter.finagle.Filter.TypeAgnostic): ReqRepServicePerEndpoint =
      ReqRepServicePerEndpoint.apply(makeRequest).filtered(filter)

    /**
     * Converts the `ServicePerEndpoint` to a `GeneratedThriftService`.
     * @see _root_.com.twitter.scrooge.ToThriftService
     */
    def toThriftService: _root_.com.twitter.finagle.thrift.ThriftService = ReqRepMethodPerEndpoint(this)

    /**
     * Used to close the underlying `Service`.
     * Not a user-defined API.
     */
    def asClosable: _root_.com.twitter.util.Closable = _root_.com.twitter.util.Closable.nop
  }

  @deprecated("Use ServicePerEndpoint", "2017-11-07")
  trait BaseServiceIface extends ToThriftService {
    def makeRequest : com.twitter.finagle.Service[self.MakeRequest.Args, self.MakeRequest.SuccessType]

    def toThriftService: _root_.com.twitter.finagle.thrift.ThriftService = new MethodIface(this)
  }

  object ServicePerEndpoint {

    def apply(
      makeRequest : _root_.com.twitter.finagle.Service[self.MakeRequest.Args, self.MakeRequest.SuccessType]
    ): ServicePerEndpoint = new ServicePerEndpointImpl(makeRequest)

    private final class ServicePerEndpointImpl(
      override val makeRequest : _root_.com.twitter.finagle.Service[self.MakeRequest.Args, self.MakeRequest.SuccessType]
    ) extends ServicePerEndpoint {

      override def withMakeRequest(
        makeRequest : _root_.com.twitter.finagle.Service[self.MakeRequest.Args, self.MakeRequest.SuccessType]
      ): ServicePerEndpoint =
        new ServicePerEndpointImpl(makeRequest)

      override def filtered(filter: _root_.com.twitter.finagle.Filter.TypeAgnostic): ServicePerEndpoint =
        new ServicePerEndpointImpl(
          makeRequest = filter.toFilter.andThen(makeRequest)
        )

      override def asClosable: _root_.com.twitter.util.Closable =
        _root_.com.twitter.util.Closable.all(
          this.makeRequest
        )
    }
  }

  object ReqRepServicePerEndpoint {

    def apply(
      makeRequest :  _root_.com.twitter.finagle.Service[_root_.com.twitter.scrooge.Request[self.MakeRequest.Args], _root_.com.twitter.scrooge.Response[self.MakeRequest.SuccessType]]
    ): ReqRepServicePerEndpoint =
      new ReqRepServicePerEndpointImpl(makeRequest)

    private final class ReqRepServicePerEndpointImpl(
      override val makeRequest : _root_.com.twitter.finagle.Service[_root_.com.twitter.scrooge.Request[self.MakeRequest.Args], _root_.com.twitter.scrooge.Response[self.MakeRequest.SuccessType]]
    ) extends ReqRepServicePerEndpoint {

      override def withMakeRequest(
        makeRequest : _root_.com.twitter.finagle.Service[com.twitter.scrooge.Request[self.MakeRequest.Args], _root_.com.twitter.scrooge.Response[self.MakeRequest.SuccessType]]
      ): ReqRepServicePerEndpoint =
        new ReqRepServicePerEndpointImpl(makeRequest)

      override def filtered(filter: com.twitter.finagle.Filter.TypeAgnostic): ReqRepServicePerEndpoint =
        new ReqRepServicePerEndpointImpl(
          makeRequest = filter.toFilter.andThen(makeRequest)
        )

      override def asClosable: _root_.com.twitter.util.Closable =
        _root_.com.twitter.util.Closable.all(
          this.makeRequest
        )
    }
  }

  def unsafeBuildFromMethods(methods: immutable$Map[ThriftMethod,  _root_.com.twitter.finagle.Service[_root_.com.twitter.scrooge.Request[_], _root_.com.twitter.scrooge.Response[_]]]): ReqRepServicePerEndpoint = {
    val makeRequest = {
      val makeRequestOpt = methods.get(self.MakeRequest)
      if (makeRequestOpt.isEmpty) throw new IllegalArgumentException(_root_.java.lang.String.format("No implementation found for method MakeRequest in %s", methods.keySet))
      makeRequestOpt.get.asInstanceOf[self.MakeRequest.ReqRepServicePerEndpointServiceType]
    }

    ReqRepServicePerEndpoint(makeRequest)
  }

  @deprecated("Use ServicePerEndpoint", "2017-11-07")
  case class ServiceIface(
    makeRequest : com.twitter.finagle.Service[self.MakeRequest.Args, self.MakeRequest.SuccessType]
  ) extends BaseServiceIface
    with _root_.com.twitter.finagle.thrift.service.Filterable[ServiceIface] {

    /**
     * Prepends the given type-agnostic `Filter` to all of the `Services`
     * and returns a copy of the `ServiceIface` now including the filter.
     */
    def filtered(filter: com.twitter.finagle.Filter.TypeAgnostic): ServiceIface =
      copy(
        makeRequest = filter.toFilter.andThen(makeRequest)
      )
  }

  implicit object ServicePerEndpointBuilder
    extends _root_.com.twitter.finagle.thrift.service.ServicePerEndpointBuilder[ServicePerEndpoint] {
      override def serviceClass: Class[ServicePerEndpoint] = classOf[ServicePerEndpoint]
      def servicePerEndpoint(
        thriftService: _root_.com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
        clientParam: RichClientParam
      ): ServicePerEndpoint =
        ServicePerEndpoint(
          makeRequest = _root_.com.twitter.finagle.thrift.service.ThriftServicePerEndpoint(
            self.MakeRequest,
            thriftService,
            clientParam
          )
        )
  }

  implicit object ReqRepServicePerEndpointBuilder
    extends _root_.com.twitter.finagle.thrift.service.ReqRepServicePerEndpointBuilder[ReqRepServicePerEndpoint] {
      override def serviceClass: Class[ReqRepServicePerEndpoint] = classOf[ReqRepServicePerEndpoint]
      def servicePerEndpoint(
        thriftService: _root_.com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
        clientParam: RichClientParam
      ): ReqRepServicePerEndpoint =
        ReqRepServicePerEndpoint(
          makeRequest = _root_.com.twitter.finagle.thrift.service.ThriftReqRepServicePerEndpoint(self.MakeRequest, thriftService, clientParam)
        )
  }

  @deprecated("Use ServicePerEndpointBuilder", "2017-11-07")
  implicit object ServiceIfaceBuilder
    extends com.twitter.finagle.thrift.ServiceIfaceBuilder[ServiceIface] {
      override def serviceClass: Class[ServiceIface] = classOf[ServiceIface]
      def newServiceIface(
        binaryService: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
        clientParam: RichClientParam
      ): ServiceIface =
        ServiceIface(
          makeRequest = _root_.com.twitter.finagle.thrift.service.ThriftServicePerEndpoint(
            self.MakeRequest,
            binaryService,
            clientParam
          )
        )
  }

  object MakeRequest extends ThriftMethod {
    
    object Args extends ValidatingThriftStructCodec3[Args] with StructBuilderFactory[Args] {
      val Struct: TStruct = new TStruct("makeRequest_args")
      val RequestField: TField = new TField("request", TType.STRUCT, 1)
      val RequestFieldManifest: Manifest[example.thrift.SimpleRequest] = manifest[example.thrift.SimpleRequest]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          RequestField,
          false,
          true,
          RequestFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String],
          None,
          _root_.scala.Option(example.thrift.SimpleRequest.unsafeEmpty)
        )
      )
    
    
      val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      private val fieldTypes: IndexedSeq[ClassTag[_]] = IndexedSeq[ClassTag[_]](
        classTag[example.thrift.SimpleRequest].asInstanceOf[ClassTag[_]]
      )
    
      private[this] val structFields: Seq[ThriftStructField[Args]] = Seq[ThriftStructField[Args]](
        new ThriftStructField[Args](
          RequestField,
          _root_.scala.Some(RequestFieldManifest),
          classOf[Args]) {
            def getValue[R](struct: Args): R = struct.request.asInstanceOf[R]
        }
      )
    
      override lazy val metaData: ThriftStructMetaData[Args] =
        ThriftStructMetaData(this, structFields, fieldInfos, Nil, structAnnotations)
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Args): Unit = {
        if (_item.request eq null) throw new TProtocolException("Required field request cannot be null")
      }
    
      /**
       * Checks that the struct is a valid as a new instance. If there are any missing required or
       * construction required fields, return a non-empty list.
       */
      def validateNewInstance(item: Args): scala.Seq[com.twitter.scrooge.validation.Issue] = {
        val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]
    
        if (item.request eq null)
          buf += com.twitter.scrooge.validation.MissingRequiredField(fieldInfos.apply(0))
        buf ++= validateField(item.request)
        buf.toList
      }
    
      /**
       * Validate that all validation annotations on the struct meet the criteria defined in the
       * corresponding [[com.twitter.scrooge.validation.ThriftConstraintValidator]].
       */
      def validateInstanceValue(item: Args): Set[com.twitter.scrooge.thrift_validation.ThriftValidationViolation] = {
        val violations = scala.collection.mutable.Set.empty[com.twitter.scrooge.thrift_validation.ThriftValidationViolation]
        violations ++= validateFieldValue("request", item.request, fieldInfos.apply(0).fieldAnnotations, scala.None)
        violations.toSet
      }
    
      def withoutPassthroughFields(original: Args): Args =
        new Args(
          request =
            {
              val field = original.request
              example.thrift.SimpleRequest.withoutPassthroughFields(field)
            }
        )
    
      lazy val unsafeEmpty: Args = {
        val request: example.thrift.SimpleRequest = example.thrift.SimpleRequest.unsafeEmpty
    
        new Args(
          request,
          _root_.com.twitter.scrooge.internal.TProtocols.NoPassthroughFields
        )
      }
    
      def newBuilder(): StructBuilder[Args] = new ArgsStructBuilder(_root_.scala.None, fieldTypes)
    
      override def encode(_item: Args, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
    
      override def decode(_iprot: TProtocol): Args = {
        decodeInternal(_iprot, false)
      }
    
      private[this] def decodeInternal(_iprot: TProtocol, lazily: Boolean): Args = {
        var request: example.thrift.SimpleRequest = null
        var _got_request = false
    
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        do {
          val _field = _iprot.readFieldBegin()
          val _fieldType = _field.`type`
          if (_fieldType == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 1 =>
                _root_.com.twitter.scrooge.internal.TProtocols.validateFieldType(TType.STRUCT, _fieldType, "request")
                request = example.thrift.SimpleRequest.decode(_iprot)
                _got_request = true
              case _ =>
                _passthroughFields = _root_.com.twitter.scrooge.internal.TProtocols.readPassthroughField(_iprot, _field, _passthroughFields)
            }
            _iprot.readFieldEnd()
          }
        } while (!_done)
        _iprot.readStructEnd()
    
        if (!_got_request) _root_.com.twitter.scrooge.internal.TProtocols.throwMissingRequiredField("Args", "request")
    
        val _passthroughFieldsResult =
          if (_passthroughFields eq null) _root_.com.twitter.scrooge.internal.TProtocols.NoPassthroughFields
          else _passthroughFields.result()
        new Args(
          request,
          _passthroughFieldsResult
        )
      }
    
      def apply(
        request: example.thrift.SimpleRequest
      ): Args =
        new Args(
          request
        )
    
      def unapply(_item: Args): _root_.scala.Option[example.thrift.SimpleRequest] = _root_.scala.Some(_item.request)
    
    
    
    }
    
    class Args(
        val request: example.thrift.SimpleRequest,
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftStruct
      with _root_.scala.Product1[example.thrift.SimpleRequest]
      with ValidatingThriftStruct[Args]
      with java.io.Serializable
    {
      import Args._
    
      def this(
        request: example.thrift.SimpleRequest
      ) = this(
        request,
        immutable$Map.empty
      )
    
      def _1: example.thrift.SimpleRequest = request
    
    
    
      override def write(_oprot: TProtocol): Unit = {
        Args.validate(this)
        _oprot.writeStructBegin(Struct)
        if (request ne null) {
          _oprot.writeFieldBegin(RequestField)
          request.write(_oprot)
          _oprot.writeFieldEnd()
        }
        _root_.com.twitter.scrooge.internal.TProtocols.finishWritingStruct(_oprot, _passthroughFields)
      }
    
      def copy(
        request: example.thrift.SimpleRequest = this.request,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Args =
        new Args(
          request,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Args]
    
      private[this] def _equals(other: Args): Boolean =
          this.productArity == other.productArity &&
          this.productIterator.sameElements(other.productIterator) &&
          this._passthroughFields == other._passthroughFields
    
      override def equals(other: Any): Boolean =
        canEqual(other) && _equals(other.asInstanceOf[Args])
    
      override def hashCode: Int = {
        _root_.scala.runtime.ScalaRunTime._hashCode(this)
      }
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
      override def productPrefix: String = "Args"
    
      def _codec: ValidatingThriftStructCodec3[Args] = Args
    
      def newBuilder(): StructBuilder[Args] = new ArgsStructBuilder(_root_.scala.Some(this), fieldTypes)
    }
    
    private[thrift] class ArgsStructBuilder(instance: _root_.scala.Option[Args], fieldTypes: IndexedSeq[ClassTag[_]])
        extends StructBuilder[Args](fieldTypes) {
    
      def build(): Args = {
        val _fieldArray = fieldArray // shadow variable
        if (instance.isDefined) {
          val instanceValue = instance.get
          Args(
            if (_fieldArray(0) == null) instanceValue.request else _fieldArray(0).asInstanceOf[example.thrift.SimpleRequest]
          )
        } else {
          if (genericArrayOps(_fieldArray).contains(null)) throw new InvalidFieldsException(structBuildError("Args"))
          Args(
            _fieldArray(0).asInstanceOf[example.thrift.SimpleRequest]
          )
        }
      }
    }

    type SuccessType = example.thrift.SimpleResponse
    
    object Result extends ValidatingThriftStructCodec3[Result] with StructBuilderFactory[Result] {
      val Struct: TStruct = new TStruct("makeRequest_result")
      val SuccessField: TField = new TField("success", TType.STRUCT, 0)
      val SuccessFieldManifest: Manifest[example.thrift.SimpleResponse] = manifest[example.thrift.SimpleResponse]
    
      /**
       * Field information in declaration order.
       */
      lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
        new ThriftStructFieldInfo(
          SuccessField,
          true,
          false,
          SuccessFieldManifest,
          _root_.scala.None,
          _root_.scala.None,
          immutable$Map.empty[String, String],
          immutable$Map.empty[String, String],
          None,
          _root_.scala.Option(example.thrift.SimpleResponse.unsafeEmpty)
        )
      )
    
    
      val structAnnotations: immutable$Map[String, String] =
        immutable$Map.empty[String, String]
    
      private val fieldTypes: IndexedSeq[ClassTag[_]] = IndexedSeq[ClassTag[_]](
        classTag[_root_.scala.Option[example.thrift.SimpleResponse]].asInstanceOf[ClassTag[_]]
      )
    
      private[this] val structFields: Seq[ThriftStructField[Result]] = Seq[ThriftStructField[Result]](
        new ThriftStructField[Result](
          SuccessField,
          _root_.scala.Some(SuccessFieldManifest),
          classOf[Result]) {
            def getValue[R](struct: Result): R = struct.success.asInstanceOf[R]
        }
      )
    
      override lazy val metaData: ThriftStructMetaData[Result] =
        ThriftStructMetaData(this, structFields, fieldInfos, Nil, structAnnotations)
    
      /**
       * Checks that all required fields are non-null.
       */
      def validate(_item: Result): Unit = {
      }
    
      /**
       * Checks that the struct is a valid as a new instance. If there are any missing required or
       * construction required fields, return a non-empty list.
       */
      def validateNewInstance(item: Result): scala.Seq[com.twitter.scrooge.validation.Issue] = {
        val buf = scala.collection.mutable.ListBuffer.empty[com.twitter.scrooge.validation.Issue]
    
        buf ++= validateField(item.success)
        buf.toList
      }
    
      /**
       * Validate that all validation annotations on the struct meet the criteria defined in the
       * corresponding [[com.twitter.scrooge.validation.ThriftConstraintValidator]].
       */
      def validateInstanceValue(item: Result): Set[com.twitter.scrooge.thrift_validation.ThriftValidationViolation] = {
        val violations = scala.collection.mutable.Set.empty[com.twitter.scrooge.thrift_validation.ThriftValidationViolation]
        violations ++= validateFieldValue("success", item.success, fieldInfos.apply(0).fieldAnnotations, scala.None)
        violations.toSet
      }
    
      def withoutPassthroughFields(original: Result): Result =
        new Result(
          success =
            {
              val field = original.success
              field.map { field =>
                example.thrift.SimpleResponse.withoutPassthroughFields(field)
              }
            }
        )
    
      lazy val unsafeEmpty: Result = {
        val success: _root_.scala.Option[example.thrift.SimpleResponse] = _root_.scala.None
    
        new Result(
          success,
          _root_.com.twitter.scrooge.internal.TProtocols.NoPassthroughFields
        )
      }
    
      def newBuilder(): StructBuilder[Result] = new ResultStructBuilder(_root_.scala.None, fieldTypes)
    
      override def encode(_item: Result, _oproto: TProtocol): Unit = {
        _item.write(_oproto)
      }
    
    
      override def decode(_iprot: TProtocol): Result = {
        decodeInternal(_iprot, false)
      }
    
      private[this] def decodeInternal(_iprot: TProtocol, lazily: Boolean): Result = {
        var success: Option[example.thrift.SimpleResponse] = None
    
        var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
        var _done = false
    
        _iprot.readStructBegin()
        do {
          val _field = _iprot.readFieldBegin()
          val _fieldType = _field.`type`
          if (_fieldType == TType.STOP) {
            _done = true
          } else {
            _field.id match {
              case 0 =>
                _root_.com.twitter.scrooge.internal.TProtocols.validateFieldType(TType.STRUCT, _fieldType, "success")
                success = _root_.scala.Some(example.thrift.SimpleResponse.decode(_iprot))
              case _ =>
                _passthroughFields = _root_.com.twitter.scrooge.internal.TProtocols.readPassthroughField(_iprot, _field, _passthroughFields)
            }
            _iprot.readFieldEnd()
          }
        } while (!_done)
        _iprot.readStructEnd()
    
    
        val _passthroughFieldsResult =
          if (_passthroughFields eq null) _root_.com.twitter.scrooge.internal.TProtocols.NoPassthroughFields
          else _passthroughFields.result()
        new Result(
          success,
          _passthroughFieldsResult
        )
      }
    
      def apply(
        success: _root_.scala.Option[example.thrift.SimpleResponse] = _root_.scala.None
      ): Result =
        new Result(
          success
        )
    
      def unapply(_item: Result): _root_.scala.Option[_root_.scala.Option[example.thrift.SimpleResponse]] = _root_.scala.Some(_item.success)
    
    
    
    }
    
    class Result(
        val success: _root_.scala.Option[example.thrift.SimpleResponse],
        val _passthroughFields: immutable$Map[Short, TFieldBlob])
      extends ThriftResponse[example.thrift.SimpleResponse] with ThriftStruct
      with _root_.scala.Product1[Option[example.thrift.SimpleResponse]]
      with ValidatingThriftStruct[Result]
      with java.io.Serializable
    {
      import Result._
    
      def this(
        success: _root_.scala.Option[example.thrift.SimpleResponse] = _root_.scala.None
      ) = this(
        success,
        immutable$Map.empty
      )
    
      def _1: _root_.scala.Option[example.thrift.SimpleResponse] = success
    
      def successField: Option[example.thrift.SimpleResponse] = success
      def exceptionFields: Iterable[Option[com.twitter.scrooge.ThriftException]] = Nil
    
    
      override def write(_oprot: TProtocol): Unit = {
        Result.validate(this)
        _oprot.writeStructBegin(Struct)
        if (success.isDefined) {
          _oprot.writeFieldBegin(SuccessField)
          success.get.write(_oprot)
          _oprot.writeFieldEnd()
        }
        _root_.com.twitter.scrooge.internal.TProtocols.finishWritingStruct(_oprot, _passthroughFields)
      }
    
      def copy(
        success: _root_.scala.Option[example.thrift.SimpleResponse] = this.success,
        _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
      ): Result =
        new Result(
          success,
          _passthroughFields
        )
    
      override def canEqual(other: Any): Boolean = other.isInstanceOf[Result]
    
      private[this] def _equals(other: Result): Boolean =
          this.productArity == other.productArity &&
          this.productIterator.sameElements(other.productIterator) &&
          this._passthroughFields == other._passthroughFields
    
      override def equals(other: Any): Boolean =
        canEqual(other) && _equals(other.asInstanceOf[Result])
    
      override def hashCode: Int = {
        _root_.scala.runtime.ScalaRunTime._hashCode(this)
      }
    
      override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)
    
      override def productPrefix: String = "Result"
    
      def _codec: ValidatingThriftStructCodec3[Result] = Result
    
      def newBuilder(): StructBuilder[Result] = new ResultStructBuilder(_root_.scala.Some(this), fieldTypes)
    }
    
    private[thrift] class ResultStructBuilder(instance: _root_.scala.Option[Result], fieldTypes: IndexedSeq[ClassTag[_]])
        extends StructBuilder[Result](fieldTypes) {
    
      def build(): Result = {
        val _fieldArray = fieldArray // shadow variable
        if (instance.isDefined) {
          val instanceValue = instance.get
          Result(
            if (_fieldArray(0) == null) instanceValue.success else _fieldArray(0).asInstanceOf[_root_.scala.Option[example.thrift.SimpleResponse]]
          )
        } else {
          if (genericArrayOps(_fieldArray).contains(null)) throw new InvalidFieldsException(structBuildError("Result"))
          Result(
            _fieldArray(0).asInstanceOf[_root_.scala.Option[example.thrift.SimpleResponse]]
          )
        }
      }
    }

    val annotations: immutable$Map[String, String] = immutable$Map.empty

    type FunctionType = Function1[Args,Future[example.thrift.SimpleResponse]]
    type ReqRepFunctionType = Function1[_root_.com.twitter.scrooge.Request[Args],Future[_root_.com.twitter.scrooge.Response[example.thrift.SimpleResponse]]]

    type ServicePerEndpointServiceType = _root_.com.twitter.finagle.Service[Args, SuccessType]
    type ReqRepServicePerEndpointServiceType = _root_.com.twitter.finagle.Service[_root_.com.twitter.scrooge.Request[Args], _root_.com.twitter.scrooge.Response[SuccessType]]

    def toServicePerEndpointService(f: FunctionType): ServicePerEndpointServiceType =
      _root_.com.twitter.finagle.Service.mk { args: Args =>
        f(args)
      }

    def toReqRepServicePerEndpointService(f: ReqRepFunctionType): ReqRepServicePerEndpointServiceType =
      _root_.com.twitter.finagle.Service.mk[_root_.com.twitter.scrooge.Request[Args], _root_.com.twitter.scrooge.Response[SuccessType]] { request: _root_.com.twitter.scrooge.Request[Args] =>
        f(request)
      }


    val name: String = "MakeRequest"
    val serviceName: String = "SimpleService"
    val argsCodec: Args.type = Args
    val responseCodec: Result.type = Result
    val oneway: Boolean = false
  }

  // Compatibility aliases.
  val makeRequest$args: MakeRequest.Args.type = MakeRequest.Args
  type makeRequest$args = MakeRequest.Args

  val makeRequest$result: MakeRequest.Result.type = MakeRequest.Result
  type makeRequest$result = MakeRequest.Result


  trait SimpleService[F[_]] extends _root_.com.twitter.finagle.thrift.ThriftService {
    
    def makeRequest(request: example.thrift.SimpleRequest): F[example.thrift.SimpleResponse]
    /**
     * Used to close the underlying `Service`.
     * Not a user-defined API.
     */
    def asClosable: _root_.com.twitter.util.Closable = _root_.com.twitter.util.Closable.nop
  }

  object SimpleService {
    implicit def SimpleServiceInReaderT[F[_]]: SimpleService[({type Λ[β0] = _root_.cats.data.ReaderT[F, SimpleService[F], β0]})#Λ] =
      _root_.cats.tagless.Derive.readerT[SimpleService, F]

    implicit val SimpleServiceInstrument: _root_.cats.tagless.aop.Instrument[SimpleService] = _root_.cats.tagless.Derive.instrument[SimpleService]

    implicit def SimpleServiceHigherKindedToMethodPerEndpoint: _root_.com.dwolla.util.async.finagle.HigherKindedToMethodPerEndpoint[SimpleService] =
      new _root_.com.dwolla.util.async.finagle.HigherKindedToMethodPerEndpoint[SimpleService] {
        override type MPE = MethodPerEndpoint
        override val mpeClassTag: _root_.scala.reflect.ClassTag[MethodPerEndpoint] = _root_.scala.reflect.classTag[MethodPerEndpoint]
        override def toMethodPerEndpoint(hk: SimpleService[_root_.com.twitter.util.Future]): MethodPerEndpoint = MethodPerEndpoint(hk)
      }

  }

  trait MethodPerEndpoint extends SimpleService[Future]

  object MethodPerEndpoint {
    def apply(fa: SimpleService[_root_.com.twitter.util.Future]): MethodPerEndpoint = new MethodPerEndpoint {
      override def makeRequest(request: example.thrift.SimpleRequest): Future[example.thrift.SimpleResponse] = fa.makeRequest(request)
    }

    def apply(servicePerEndpoint: ServicePerEndpoint): MethodPerEndpoint = {
      new MethodPerEndpointImpl(servicePerEndpoint) {}
    }

    /**
     * Use `MethodPerEndpoint.apply()` instead of this constructor.
     */
    class MethodPerEndpointImpl protected (servicePerEndpoint: ServicePerEndpoint)
      extends MethodPerEndpoint {
        def makeRequest(request: example.thrift.SimpleRequest): Future[example.thrift.SimpleResponse] =
          servicePerEndpoint.makeRequest(self.MakeRequest.Args(request))

        override def asClosable: _root_.com.twitter.util.Closable =
          servicePerEndpoint.asClosable
    }
  }

  object ReqRepMethodPerEndpoint {

    def apply(servicePerEndpoint: ReqRepServicePerEndpoint): MethodPerEndpoint =
      new ReqRepMethodPerEndpointImpl(servicePerEndpoint) { }

    /**
     * Use `ReqRepMethodPerEndpoint.apply()` instead of this constructor.
     */
    class ReqRepMethodPerEndpointImpl protected (servicePerEndpoint: ReqRepServicePerEndpoint)
      extends MethodPerEndpoint {

        def makeRequest(request: example.thrift.SimpleRequest): Future[example.thrift.SimpleResponse] = {
          val requestCtx = _root_.com.twitter.finagle.context.Contexts.local.getOrElse(_root_.com.twitter.finagle.thrift.Headers.Request.Key, () => _root_.com.twitter.finagle.thrift.Headers.Request.newValues)
          val scroogeRequest = _root_.com.twitter.scrooge.Request(requestCtx.values, self.MakeRequest.Args(request))
          servicePerEndpoint.makeRequest(scroogeRequest).transform(_root_.com.twitter.finagle.thrift.service.ThriftReqRepServicePerEndpoint.transformResult)
        }

        override def asClosable: _root_.com.twitter.util.Closable =
          servicePerEndpoint.asClosable
    }
  }

  @deprecated("Use MethodPerEndpoint", "2017-11-07")
  class MethodIface(serviceIface: BaseServiceIface)
    extends MethodPerEndpoint {
    def makeRequest(request: example.thrift.SimpleRequest): Future[example.thrift.SimpleResponse] =
      serviceIface.makeRequest(self.MakeRequest.Args(request))
  }

  implicit object MethodPerEndpointBuilder
    extends _root_.com.twitter.finagle.thrift.service.MethodPerEndpointBuilder[ServicePerEndpoint, MethodPerEndpoint] {
    def methodPerEndpoint(servicePerEndpoint: ServicePerEndpoint): MethodPerEndpoint =
      MethodPerEndpoint(servicePerEndpoint)
  }

  implicit object ReqRepMethodPerEndpointBuilder
    extends _root_.com.twitter.finagle.thrift.service.ReqRepMethodPerEndpointBuilder[ReqRepServicePerEndpoint, MethodPerEndpoint] {
    def methodPerEndpoint(servicePerEndpoint: ReqRepServicePerEndpoint): MethodPerEndpoint =
      ReqRepMethodPerEndpoint(servicePerEndpoint)
  }

  class FinagledClient(
      service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
      clientParam: RichClientParam)
    extends SimpleService$FinagleClient(service, clientParam)
    with MethodPerEndpoint {

    @deprecated("Use com.twitter.finagle.thrift.RichClientParam", "2017-08-16")
    def this(
      service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
      protocolFactory: org.apache.thrift.protocol.TProtocolFactory = Protocols.binaryFactory(),
      serviceName: String = "SimpleService",
      stats: com.twitter.finagle.stats.StatsReceiver = com.twitter.finagle.stats.NullStatsReceiver,
      responseClassifier: ctfs.ResponseClassifier = ctfs.ResponseClassifier.Default
    ) = this(
      service,
      RichClientParam(
        protocolFactory,
        serviceName,
        clientStats = stats,
        responseClassifier = responseClassifier
      )
    )

    @deprecated("Use com.twitter.finagle.thrift.RichClientParam", "2017-08-16")
    def this(
      service: com.twitter.finagle.Service[ThriftClientRequest, Array[Byte]],
      protocolFactory: org.apache.thrift.protocol.TProtocolFactory,
      serviceName: String,
      stats: com.twitter.finagle.stats.StatsReceiver
    ) = this(
      service,
      RichClientParam(
        protocolFactory,
        serviceName,
        clientStats = stats
      )
    )
  }

  class FinagledService(
      iface: MethodPerEndpoint,
      serverParam: RichServerParam)
    extends SimpleService$FinagleService(iface, serverParam) {

    @deprecated("Use com.twitter.finagle.thrift.RichServerParam", "2017-08-16")
    def this(
      iface: MethodPerEndpoint,
      protocolFactory: org.apache.thrift.protocol.TProtocolFactory,
      serviceName: String = "SimpleService"
    ) = this(iface, RichServerParam(protocolFactory, serviceName))
  }

  class Filter(serverParam: RichServerParam) {
    private[this] def protocolFactory: TProtocolFactory = serverParam.restrictedProtocolFactory

    private[this] def serviceName: String = serverParam.serviceName
    private[this] def responseClassifier: ctfs.ResponseClassifier = serverParam.responseClassifier
    private[this] def stats: StatsReceiver = serverParam.serverStats
    private[this] def perEndpointStats: Boolean = serverParam.perEndpointStats && !stats.isNull

    private[this] val tlReusableBuffer: TReusableBuffer = TReusableBuffer(maxThriftBufferSize = serverParam.maxThriftBufferSize)

    private[thrift] def exception(name: String, seqid: Int, code: Int, message: String): Buf = {
      val x = new TApplicationException(code, message)
      val memoryBuffer = tlReusableBuffer.get()
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.EXCEPTION, seqid))
        x.write(oprot)
        oprot.writeMessageEnd()
        oprot.getTransport.flush()

        // make a copy of the array of bytes to construct a new buffer because memoryBuffer is reusable
        Buf.ByteArray.Shared(memoryBuffer.getArray(), 0, memoryBuffer.length())
      } finally {
        tlReusableBuffer.reset()
      }
    }

    private[this] def reply(name: String, seqid: Int, result: ThriftStruct): Buf = {
      val memoryBuffer = tlReusableBuffer.get()
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)
        val start = System.nanoTime
        oprot.writeMessageBegin(new TMessage(name, TMessageType.REPLY, seqid))
        result.write(oprot)
        oprot.writeMessageEnd()
        val trace = _root_.com.twitter.finagle.tracing.Trace()
        if (trace.isActivelyTracing) {
          trace.recordBinary("srv/response_serialization_ns", System.nanoTime - start)
        }
        oprot.getTransport.flush()

        // make a copy of the array of bytes to construct a new buffer because memoryBuffer is reusable
        Buf.ByteArray.Shared(memoryBuffer.getArray(), 0, memoryBuffer.length())
      } finally {
        tlReusableBuffer.reset()
      }
    }

    private[this] def recordResponse(reqRep: ctfs.ReqRep, methodStats: _root_.com.twitter.finagle.thrift.ThriftMethodStats): Unit = {
      ServerToReqRep.setCtx(reqRep)
      val classified = responseClassifier.applyOrElse(reqRep, ctfs.ResponseClassifier.Default)
      if (classified.isInstanceOf[ctfs.ResponseClass.Successful]) {
        methodStats.successCounter.incr()
      } else if (classified.isInstanceOf[ctfs.ResponseClass.Failed]) {
        methodStats.failuresCounter.incr()
        if (reqRep.response.isThrow) {
          methodStats.failuresScope.counter(Throwables.mkString(reqRep.response.throwable): _*).incr()
        }
      } // Last ResponseClass is Ignorable, which we do not need to record
    }

    final protected def perMethodStatsFilter(
      method: ThriftMethod
    ): finagle$Filter[(TProtocol, Int), Array[Byte], (TProtocol, Int), RichResponse[method.Args, method.Result]] = {
      val methodStats = if (perEndpointStats) {
        _root_.com.twitter.finagle.thrift.ThriftMethodStats((if (serviceName != "") stats.scope(serviceName) else stats).scope(method.name))
      } else {
        _root_.com.twitter.finagle.thrift.ThriftMethodStats.Null
      }

      new finagle$Filter[(TProtocol, Int), Array[Byte], (TProtocol, Int), RichResponse[method.Args, method.Result]] {
        def apply(
          req: (TProtocol, Int),
          service: finagle$Service[(TProtocol, Int), RichResponse[method.Args, method.Result]]
        ): Future[Array[Byte]] = {
          methodStats.requestsCounter.incr()
          service(req).transform { response =>
            if (response.isReturn) {
              val value = response.apply()
              if (value.isInstanceOf[SuccessfulResponse[method.Args, method.Result]]) {
                val succResp = value.asInstanceOf[SuccessfulResponse[method.Args, method.Result]]
                recordResponse(ctfs.ReqRep(succResp.input, _root_.com.twitter.util.Return(succResp.result.successField.get)), methodStats)
              } else if (value.isInstanceOf[ProtocolExceptionResponse[method.Args, method.Result]]) {
                val protExResp = value.asInstanceOf[ProtocolExceptionResponse[method.Args, method.Result]]
                recordResponse(ctfs.ReqRep(protExResp.input, _root_.com.twitter.util.Throw(protExResp.exception)), methodStats)
              } else if (value.isInstanceOf[ThriftExceptionResponse[method.Args, method.Result]]) {
                val thriftExResp = value.asInstanceOf[ThriftExceptionResponse[method.Args, method.Result]]
                val rep: Throwable = if (thriftExResp.ex.isInstanceOf[ThriftException]) {
                  _root_.com.twitter.finagle.SourcedException.setServiceName(thriftExResp.ex, serviceName)
                } else {
                  _root_.com.twitter.scrooge.internal.ApplicationExceptions.missingResult(serviceName)
                }
                recordResponse(ctfs.ReqRep(thriftExResp.input, _root_.com.twitter.util.Throw(rep)), methodStats)
              }
              Future.value(Buf.ByteArray.Owned.extract(value.response))
            } else { // Throw[_]
              recordResponse(ctfs.ReqRep(req, response), methodStats)
              Future.const(response.asInstanceOf[Throw[Array[Byte]]])
            }
          }
        }
      }
    }
    // ---- end boilerplate.

    val makeRequest: finagle$Filter[(TProtocol, Int), Array[Byte], MakeRequest.Args, MakeRequest.SuccessType] = {
      val statsFilter: finagle$Filter[(TProtocol, Int), Array[Byte], (TProtocol, Int), RichResponse[MakeRequest.Args, MakeRequest.Result]] = perMethodStatsFilter(MakeRequest)
    
      val protocolExnFilter = new SimpleFilter[(TProtocol, Int), RichResponse[MakeRequest.Args, MakeRequest.Result]] {
        def apply(
          request: (TProtocol, Int),
          service: _root_.com.twitter.finagle.Service[(TProtocol, Int), RichResponse[MakeRequest.Args, MakeRequest.Result]]
        ): Future[RichResponse[MakeRequest.Args, MakeRequest.Result]] = {
          val iprot = request._1
          val seqid = request._2
          val res = service(request)
          res.transform(resTry => {
            if (resTry.isThrow && resTry.throwable.isInstanceOf[TProtocolException]) {
              val underlyingException = resTry.throwable
              iprot.readMessageEnd()
              Future.value(
                ProtocolExceptionResponse(
                  null,
                  exception("MakeRequest", seqid, TApplicationException.PROTOCOL_ERROR, underlyingException.getMessage),
                  new TApplicationException(TApplicationException.PROTOCOL_ERROR, underlyingException.getMessage)))
            } else {
              res
            }
          })
        }
      }
    
      val serdeFilter = new finagle$Filter[(TProtocol, Int), RichResponse[MakeRequest.Args, MakeRequest.Result], MakeRequest.Args, MakeRequest.SuccessType] {
        def apply(
          request: (TProtocol, Int),
          service: _root_.com.twitter.finagle.Service[MakeRequest.Args, MakeRequest.SuccessType]
        ): Future[RichResponse[MakeRequest.Args, MakeRequest.Result]] = {
          val iprot = request._1
          val seqid = request._2
          val start = System.nanoTime
          val args = MakeRequest.Args.decode(iprot)
          iprot.readMessageEnd()
          val trace = _root_.com.twitter.finagle.tracing.Trace()
          if (trace.isActivelyTracing) {
            trace.recordBinary("srv/request_deserialization_ns", System.nanoTime - start)
          }
          _root_.com.twitter.finagle.context.Contexts.local.let(
            _root_.com.twitter.finagle.thrift.MethodMetadata.Key,
            _root_.com.twitter.finagle.thrift.MethodMetadata(MakeRequest)) {
            service(args)
          }.transform(resTry => {
            if (resTry.isReturn) {
              val methodResult = MakeRequest.Result(success = Some(resTry.apply()))
              Future.value(
                SuccessfulResponse(
                  args,
                  reply("MakeRequest", seqid, methodResult),
                  methodResult))
            } else { // Throw[_]
                Future.const(resTry.asInstanceOf[Throw[RichResponse[MakeRequest.Args, MakeRequest.Result]]])
            }
          })
        }
      }
      statsFilter.andThen(protocolExnFilter).andThen(serdeFilter)
    }
  }

}
