addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.1")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.5.0-RC2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.5.0-RC2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.5.0-RC2")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.13.2")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.11.0")
addSbtPlugin("com.eed3si9n" % "sbt-projectmatrix" % "0.9.0")
