addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.4.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.4.19")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.4.19")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.13.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.10.4")
